server:
  port: 8080

spring:
  application:
    name: account-api
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    com.kgi.account: INFO

# Made with Bob
